### PR TITLE
various improvements

### PR DESCRIPTION
**Pull request by MeDerpWasTaken**
mainly just makes stuff a bit nicer to run by adding stuff like a config file, and making the JSON files local

this might mess up some data saved for the bot so **back the important stuff up** before pulling to be safe

### CODE REVIEW

**Comment by MeDerpWasTaken** [comment]
also I disabled out the topgg stuff as installing the back did weird stuff, so someone probably should fix that soon

**Comment by jellytoaster** [comment]
> also I disabled out the topgg stuff as installing the back did weird stuff, so someone probably should fix that soon

it requires topgg api for voting system

**Comment by MeDerpWasTaken** [comment]
> > also I disabled out the topgg stuff as installing the back did weird stuff, so someone probably should fix that soon
> 
> it requires topgg api for voting system

ok, I'll look into re-adding it then. I think it installed something like old discord.py which I think might have been overriding an existing package, or something thing like that.

**Comment by jellytoaster** [comment]
:)))

**Pull request merged**
